version: '3'

services:
  catclientes:
    container_name: materias
    image : materias 
    build: .
    ports: 
      -  '5000:5000'
    depends_on:
      - mongo
  mongo:
    container_name: mongoserver
    image: mongo
    ports:
      - '27017:27017'
